spring.application.name=IT23234048
spring.data.mongodb.uri=mongodb+srv://campus_admin:system@cluster0.qt58zrc.mongodb.net/studentdb?retryWrites=true&w=majority
spring.mongodb.uri=mongodb+srv://campus_admin:system@cluster0.qt58zrc.mongodb.net/studentdb?retryWrites=true&w=majority
spring.data.mongodb.database=studentdb
spring.data.mongodb.auto-index-creation=true